### ISSUE TITLE
🚀 Versioning / Pods

### ISSUE THREAD

**Issue by jmsaulnier** [elastos/Elastos.NET.Carrier.Swift.SDK#20]
I'm working on a Flutter plugin for Carrier (https://github.com/jmsaulnier/flutter_elastos_carrier/tree/develop) so I would like to add this project as dependency (iOS) and use with CocoaPods

**Would it be possible to publish as a custom pod to Cocoapods library?**

- https://guides.cocoapods.org/making/making-a-cocoapod.html
- http://guides.cocoapods.org/syntax/podspec.html

and be able to import it in a .podspec file, for example

```
s.dependency 'Elastos.NET.Carrier.iOS.SDK', '5.1.0'
```

Linked with https://github.com/elastos/Elastos.NET.Carrier.Android.SDK/issues/29

Thanks! 🤓

**Comment by jingyu** [comment]
@jmsaulnier We will add the official release of CocoaPods in next major release. Thanks for your suggestion.

**Comment by jmsaulnier** [comment]
@jingyu Sounds great, thanks!

**Comment by jmsaulnier** [comment]
@jingyu sweet! looks like Pod install is coming soon!
https://github.com/elastos/Elastos.NET.Carrier.Demo.Remoter.iOS/commit/32418fe08af987abc526867d2fa9d154b6a00d06
Thanks @ahl0107 !

**Comment by jmsaulnier** [comment]
@stiartsly @jmsaulnier @ahl0107 Thanks 🙏
