### ISSUE TITLE
Carrier.getInstance throw error

### ISSUE THREAD

**Issue by m00c0** [elastos/Elastos.NET.Carrier.Swift.SDK#3]
# Demo Code
```
let bootstrapNode1 = BootstrapNode()
bootstrapNode1.ipv4 = "13.58.208.50"
bootstrapNode1.port = "33445"
bootstrapNode1.publicKey = "89vny8MrKdDKs7Uta9RdVmspPjnRMdwMmaiEW27pZ7gh"

let bootstrapNode2 = BootstrapNode()
bootstrapNode2.ipv4 = "18.216.102.47"
bootstrapNode2.port = "33445"
bootstrapNode2.publicKey = "G5z8MqiNDFTadFUPfMdYsYtkUDbX5mNCMVHMZtsCnFeb"

let carrierOptions = CarrierOptions()
carrierOptions.bootstrapNodes = [
   bootstrapNode1, bootstrapNode2
]
carrierOptions.udpEnabled = true
carrierOptions.persistentLocation = "ela"

do {
    let carrier = try Carrier.getInstance(options: carrierOptions, delegate: self)
    
    print("Node ID: \(carrier.getNodeId())")
    print("User ID: \(carrier.getUserId())")
    print("Address: \(carrier.getAddress())")
    
} catch _ {
    print("Failed.")
}
```

I took the values for the `BootstrapNodes` from the NodeJS example.

# Dev Environment
- Xcode 9.1
- macOS High Sierra
- iPhone Simulator (8+, iOS 11.1)

# Expected Behavior
Valid 'Carrier' object

# Actual Behavior
E/Carrier: Create native carrier instance error: 0x200000D

**Comment by stiartsly** [comment]
-- carrierOptions.persistentLocation = "ela"
Do you have write permission to directory "eta" ? Internal carrier data would be created and saved under directory "carrierOptions.persistentLocation" within Carrier.getInstance() APIs.

How to analysis on error code about value 0x200000D -->>
You can refer to error code of whisper.h in Native.SDK repository.  "2" means system facility error, and 0xD ( 13 in binary way) can be addressed as below:
#define EACCES      13  /* Permission denied */

**Comment by m00c0** [comment]
Thank you for the hint. It solved the issue.

# Solution
```
carrierOptions.persistentLocation = CarrierHelper.persistentLocation()
```
_CarrierHelper.swift_
```
private static func persistentLocation() -> String? {
   let docURL = (FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)).last
   return docURL?.absoluteString.replacingOccurrences(of: "file:///", with: "")
}
```
