### ISSUE TITLE
🤔 podspec name 

### ISSUE THREAD

**Issue by jmsaulnier** [elastos/Elastos.NET.Carrier.Swift.SDK#31]
@ahl0107 could we change the name to something like `ElastosCarrierSDK`  rather than only `carrier`
so when you import it looks like `s.dependency 'ElastosCarrierSDK', '5.2.2'`  (and then in the future we could add for example  `'ElastosWalletSDK', '1.0.2'`  `'ElastosHiveSDK', '1.0.1'` etc )

https://github.com/elastos/Elastos.NET.Carrier.iOS.SDK/blob/master/carrier.podspec#L11

Thanks 🤓

**Comment by jmsaulnier** [comment]
According to the Cocoapod docs, naming convention (and IOS in general) is camel case

**Comment by stiartsly** [comment]
The suggest has been taken, and we will update the name later. Thanks.

**Comment by jmsaulnier** [comment]
@stiartsly 🙌 thanks
