### ISSUE TITLE
🤔 podspec license

### ISSUE THREAD

**Issue by jmsaulnier** [elastos/Elastos.NET.Carrier.Swift.SDK#32]
@ahl0107 Rather than `MIT` license, shouldn't be `GPLv3` for now?

https://github.com/elastos/Elastos.NET.Carrier.iOS.SDK/blob/master/carrier.podspec#L17

Thanks 🤓

**Comment by stiartsly** [comment]
Sorry, our mistake. we corrected it on podspec.  Please check it and thanks for your reminding us.

**Comment by jmsaulnier** [comment]
@stiartsly Perfect thanks 👌
