### ISSUE TITLE
README is not updated?

### ISSUE THREAD

**Issue by voyage11** [elastos/Elastos.NET.Carrier.Swift.SDK#5]
I have built `Elastos.NET.Carrier.Native.SDK` project successfully, but I couldn't find `_dist/lipo` folder on `Elastos.NET.Carrier.Native.SDK/build/_dist`. Is this an old path? I used `_dist/iOS-x86_64`

I saw the last commit related to `libflatcc.a` removed from the project? I guess it should be removed from the README as well. 

The instruction on README can be more clear by showing the users to 
1. Create a `libs` folder inside the `NativeDistributions` folder.
2. Then, copy the 10 static libraries (`libelacarrier.a`, `libelacommon.a`, `libelasession.a`, `libflatccrt.a`, `libpj.a`, `libpjlib-util.a`, `libpjmedia.a`, `libpjnath.a`, `libsodium.a`, `libtoxcore.a`) from `Elastos.NET.Carrier.Native.SDK/build/_dist/iOS-x86_64/debug` into the `libs` folder.

**Comment by stiartsly** [comment]
1. Thank for your remind about "remove unnecessary libflatcc.a" for this repository, and I updated it to READEME.md;
2. About "_dist/lipo", It's within Native SDK repository when you use command "./dist_build.sh ios" to build all supported archs for iOS platform.

**Comment by voyage11** [comment]
I see. Thanks for the info.
